-- Daily Digest: stores one narrative summary per day, generated by Mux
-- Phase 6: Daily Digest & Reporting

CREATE TABLE IF NOT EXISTS ops_daily_digests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    digest_date DATE NOT NULL UNIQUE,
    summary TEXT NOT NULL,
    highlights JSONB NOT NULL DEFAULT '[]',
    stats JSONB NOT NULL DEFAULT '{}',
    generated_by TEXT NOT NULL DEFAULT 'mux',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_daily_digests_date ON ops_daily_digests(digest_date DESC);
