-- 033: Dream cycles — agents "dream" by recombining memories into new insights
-- Phase 11: Dream Cycle System

CREATE TABLE IF NOT EXISTS ops_dream_cycles (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id        TEXT NOT NULL,
    source_memories UUID[] NOT NULL DEFAULT '{}',
    dream_content   TEXT NOT NULL,
    dream_type      TEXT NOT NULL CHECK (dream_type IN (
        'recombination',    -- blending existing memories into new forms
        'extrapolation',    -- imagining future states from current patterns
        'contradiction',    -- finding tension between held beliefs
        'synthesis'         -- unifying disparate insights into coherent wholes
    )),
    new_memory_id   UUID REFERENCES ops_agent_memory(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Query dreams by agent, most recent first
CREATE INDEX idx_dream_cycles_agent ON ops_dream_cycles(agent_id, created_at DESC);

-- Filter by dream type
CREATE INDEX idx_dream_cycles_type ON ops_dream_cycles(dream_type);

-- Recent dreams across all agents
CREATE INDEX idx_dream_cycles_recent ON ops_dream_cycles(created_at DESC);

COMMENT ON TABLE ops_dream_cycles IS 'Records of agent dream cycles — subconscious memory recombination';
COMMENT ON COLUMN ops_dream_cycles.source_memories IS 'UUIDs of memories used as dream seeds';
COMMENT ON COLUMN ops_dream_cycles.dream_type IS 'Classification of the dream pattern';
COMMENT ON COLUMN ops_dream_cycles.new_memory_id IS 'The new insight memory generated by the dream';
